### PR TITLE
permit http delete request with body

### LINKED ISSUE #64: Unable to include body with DELETE
The HTTP spec does not forbid bodies on DELETE methods. In fact, I am working with a third-party API that *requires* it. I would like to use maxwell, but this is a showstopper at the moment. One, for example, allows DELETE on a collection to remove multiple elements (they are listed in the body) -- it is not strictly RESTful, but HTTP is not Rest, right?

Would you consider allowing this?

https://stackoverflow.com/questions/14323716/restful-alternatives-to-delete-request-body

Just need a change in builder.ex:
```
  @method_without_body [{:get!, :get}, {:head!, :head}, {:delete!, :delete}, {:trace!, :trace}, {:options!, :options}]
  @method_with_body [{:post!, :post}, {:put!, :put}, {:patch!, :patch}]
```

### PR DESCRIPTION
**Pull request by milkwine**
Try to fix #64 
@secretworry , any suggestions? I may have time to work on it recently.

### CODE REVIEW

**Comment by zhongwencool** [comment]
Thanks 👍 
I'm curious about why test case failed on `R18`.

**Comment by milkwine** [comment]
R18 `httpc` seems not support delete with body.
https://github.com/erlang/otp/commit/0526f1a5a545d2e6be0b5ef4f2588ed81447c416#diff-89dd40e56844b997ffa9a9d90d59d5fc

**Comment by milkwine** [comment]
Hi @zhongwencool,  CI should be passed when you restart it.
Should this commit be considered?

**Comment by zhongwencool** [comment]
Release tomorrow ：）

**Pull request merged**
