### PR TITLE
fixed random module is deprecated compile warning

### PR DESCRIPTION
**Pull request by zhongwencool**

### CODE REVIEW

**Comment by secretworry** [comment]
Why don't we just implement the `unique/2` like this
```elixir
def unique(n) when n > 0, do: Enum.map(1..n, fn _ -> Enum.random(?a..?z) end) |> IO. iodata_to_binary
def unique(_), do: ""
```
The `iodata_to_binary`, which is a BIF, will save more memory, and be more effecient.

**Comment by zhongwencool** [comment]
@secretworry your solution just like：
```elixir
defp unique(size, acc\\[])
defp unique(0, acc), do: acc |> IO.iodata_to_binary
defp unique(size, acc) do
    random = Enum.random(?a..?z)
    unique(size - 1, [random|acc])
end
```
the size only 16
so two method almost the same.
when the binary is small size , it's work just as list.
`<<random, acc_binary::binary>>`  's efficiency just as  `[random|acc_list] `
So we don't need IO.iodata_to_binary/1

**Comment by secretworry** [comment]
I did a little benchmark [here](https://github.com/secretworry/benchex), my solution is slower than the one you gave. The best would be list loop + `IO.iodata_to_binary`.

**Comment by zhongwencool** [comment]
https://github.com/secretworry/benchex/pull/1
Happy to know, I will change it to list loop +`:erlang.list_to_binary` later.
@secretworry

**Pull request merged**
