### PR TITLE
Allow query strings to have nested params and arrays.

### PR DESCRIPTION
**Pull request by doughsay**
Currently, maxwell can't make requests to servers that allow arrays and nested params in query strings.  Phoenix and Rails servers (for example) all support this kind of query string, so not being able to make these kinds of requests is a big blocker for some use-cases.

To implement this, I've copied the query string encoding/decoding module from Plug, because there is no other package currently available that has this functionality.  I've opened an issue with the Plug team about it and they are ok with copy-pasting for now. (https://github.com/elixir-lang/plug/issues/539)

Let me know what you think!

(also, use [?w=1](https://github.com/zhongwencool/maxwell/pull/55/files?w=1) to see the important changes, since I fixed a few unrelated whitespace issues.)

### CODE REVIEW

**Comment by doughsay** [comment]
@zhongwencool there are 6 failing ibrowse and httpc adapter tests that were failing on a clean clone from master.  My changes shouldn't have changed anything to do with them...  Can you take a look when you have a chance?

**Comment by zhongwencool** [comment]
That's great!
Thanks @doughsay 
I will fix the failed cases tomorrow,  and merge this PR.

**Comment by doughsay** [comment]
@zhongwencool I noticed some coverage was missing from the Query module, so I also added the tests from Plug, but it seems those tests aren't running when you do `mix test`.  Manually running the tests (`mix test test/maxwell/query.exs`) works though...

**Comment by bitwalker** [comment]
The test file needs to be named `query_test.exs` for Mix to pick it up.

**Comment by doughsay** [comment]
Oh, derp!  I feel silly now...

**Comment by zhongwencool** [comment]
Thanks @doughsay  :0

**Pull request merged**
