### PR TITLE
Check for presence of body before trying to decode

### PR DESCRIPTION
**Pull request by imranismail**

### CODE REVIEW

**Comment by bitwalker** [comment]
There is another PR in the pipeline that I'd like to merge first prior to this one, as this code is impacted by it (not by much though). I'll follow up soon :)

**Comment by bitwalker** [comment]
If you rebase on master, we can get this merged :)

**Comment by imranismail** [comment]
@bitwalker rebased with a few touchups

**Comment by bitwalker** [comment]
Thanks!

**Pull request merged**
